id: P005415
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD5298
  title: 卓尼文史资料་（第四辑）
  author: ''
  volumes:
    88cb9f95667a4fa1b79ac18b44fa75ad:
      image_group_id: I1PD5307
      title: ''
      volume_number: 1
      total_pages: 189
      base_file: v001.txt
